matches:
  # Kubectl expansion, based on: 
  #   https://github.com/Dbz/kube-aliases/blob/master/kube-aliases.plugin.zsh
  # Mnemonics:
  #   k = kubectl
  #   g = get
  #   ds = describe
  #   d = delete
  #   n = nodes
  #   sa = serviceaccount
  #   s = secret
  #   p = pods
  #   e = endpoints
  #   x = exec
  #   l = logs
  #   cm = configmap
  #   a = all
  #   it = interactive terminal or -it

  - trigger: ";k;"
    replace: "kubectl "

  - trigger: ";kga;"
    replace: "kubectl get all "

  - trigger: ";kdsa;"
    replace: "kubectl describe all "

  - trigger: ";kgn;"
    replace: "kubectl get nodes "

  - trigger: ";kdsn;"
    replace: "kubectl describe nodes "

  - trigger: ";kgsa;"
    replace: "kubectl get serviceaccount "

  - trigger: ";kgs;"
    replace: "kubectl get secret "

  - trigger: ";kdss;"
    replace: "kubectl describe secret "

  - trigger: ";kgp;"
    replace: "kubectl get pods "

  - trigger: ";kdsp;"
    replace: "kubectl describe pod "

  - trigger: ";kge;"
    replace: "kubectl get endpoints "

  - trigger: ";kxit;"
    replace: "kubectl exec -it "

  - trigger: ";kl;"
    replace: "kubectl logs "

  - trigger: ";kdscm;"
    replace: "kubectl describe configmap "
